version: "3.5"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-stockchat}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    depends_on:
      - postgres
    volumes:
      - ./server/db/migrations:/migrations
    entrypoint:
      [ "migrate", "-path", "/migrations", "-database",  "postgres://postgres:postgres@postgres:5432/stockchat?sslmode=disable"]
    command: ["up"]

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

#  srv:
#    build:
#      context: ./server
#    ports:
#      - "5000:5000"
#
#  bot:
#    build:
#      context: ./bot
#    ports:
#      - "5001:5000"

#  vue:
#    build:
#      context: ./client
#    ports:
#      - "3000:3000"
volumes:
  pgdata: